# Generated by Django 4.0.4 on 2022-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profileimg/default.jpg', upload_to='media/profileimg'),
        ),
    ]
