# Generated by Django 4.0.4 on 2022-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=30)),
                ('sub_heading', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
            ],
        ),
    ]
